/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;

/**
 *
 * @author Johan Fontecha, Diana Ferraro, Andres Quintero
 */
public class Bienvenida extends javax.swing.JFrame {

    /**
     * Creates new form Bienvenida
     */
    public Bienvenida() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jblBienvenida = new javax.swing.JLabel();
        btnElegir = new javax.swing.JButton();
        jblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 2, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("En los orígenes de Älvor la única raza existente era la de los elfos. Cada 100 años nacía un elfo con capacidades extraordinarias \npara ser nombrado como nuevo líder hasta que apareciera el siguiente, pero luego de años de espera no apareció ningún elfo \nque pudiese tomar el liderazgo, ante esto los 4 altos elfos, quienes eran los encargados de educar al nuevo líder decidieron\nfabricar su propio líder, para ello tomaron a los elfos de mas bajo rango y los usaron para experimentar, a causa de esto, \nmuchos elfos murieron reduciendo la población, otros sobrevivieron pero llevaban consigo secuelas.\n\nDe estos experimentos nacieron distintos tipos de seres, había unos seres con apariencia humana, pero estos solo llegaban \na la altura de la cintura de un elfo y no poseían nada más que fuerza, también aparecieron seres que poseían una piel verde,\neran enormes y muy feos, por otro lado, aparecieron unos seres como humanos corrientes sin embargo unos poseían\nhabilidades mágicas y otros no, lamentablemente al no poseer la apariencia de un elfo fueron descartados y enviados al\nbosque a morir. Los seres que lograron sobrevivir se escondieron en las montañas planeando como vencer a los 4 altos elfos,\nfinalmente luego de una fuerte batalla estos fueron derrotados y los mismos seres decidieron dividir el territorio para que \ncada raza nacida se ubicase allí y se hiciera cargo del territorio.");
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextArea1.setFocusTraversalPolicyProvider(true);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 800, 270));

        jblBienvenida.setBackground(new java.awt.Color(220, 213, 203));
        jblBienvenida.setFont(new java.awt.Font("Castellar", 1, 48)); // NOI18N
        jblBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblBienvenida.setText("BIENVENIDO A \"ÄLVOR\"");
        jblBienvenida.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.lightGray, null, null));
        jblBienvenida.setOpaque(true);
        jPanel1.add(jblBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 84, 690, 70));

        btnElegir.setBackground(new java.awt.Color(220, 213, 203));
        btnElegir.setFont(new java.awt.Font("Castellar", 1, 24)); // NOI18N
        btnElegir.setText("Elegir personaje");
        btnElegir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnElegir.setBorderPainted(false);
        btnElegir.setFocusPainted(false);
        btnElegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElegirActionPerformed(evt);
            }
        });
        jPanel1.add(btnElegir, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 490, 290, 40));
        btnElegir.getAccessibleContext().setAccessibleName(" Elegir personaje ");

        jblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"))); // NOI18N
        jPanel1.add(jblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 674));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnElegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElegirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnElegirActionPerformed


     public JButton getBtnElegir() {
        return btnElegir;
    }

    public void setBtnElegir(JButton btnElegir) {
        this.btnElegir = btnElegir;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnElegir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel jblBienvenida;
    private javax.swing.JLabel jblFondo;
    // End of variables declaration//GEN-END:variables
}
