/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Personaje;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Johan Fontecha, Diana Ferraro, Andres Quintero
 */
public class frmFinal extends javax.swing.JFrame {

    /**
     * Creates new form frmFinal
     */
    private Personaje[] lista;
    private int iterador;
    public frmFinal() {
        initComponents();
    }
    
    public void setLista(Personaje[] list ){
        this.lista=list;
        System.out.println(list.length+"  es la distancia");
        jblPersonaje.setIcon(new javax.swing.ImageIcon(getClass().getResource(this.lista[0].getLinkImag())));
        jblArma.setIcon(new javax.swing.ImageIcon(getClass().getResource(this.lista[0].getLinkArma())));
        this.iterador=0;
        this.jblNombArma.setText(this.lista[0].getNombreArma());
        this.JTxtEstadisticas.setText(("Para el "+this.lista[0].getRaza()+" numero 1\n"+this.lista[0].getInfo()));
        this.jblArmadura.setIcon(new javax.swing.ImageIcon(getClass().getResource(this.lista[0].getLinkArmor())));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTxtEstadisticas = new javax.swing.JTextArea();
        btnVolver = new javax.swing.JButton();
        jblPersonaje = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        btnAdelante = new javax.swing.JButton();
        jblNombArma = new javax.swing.JLabel();
        jblArma = new javax.swing.JLabel();
        jblArmadura = new javax.swing.JLabel();
        jblNombArmadura = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jblFondo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JTxtEstadisticas.setBackground(new java.awt.Color(220, 213, 203));
        JTxtEstadisticas.setColumns(20);
        JTxtEstadisticas.setFont(new java.awt.Font("Papyrus", 1, 13)); // NOI18N
        JTxtEstadisticas.setRows(5);
        JTxtEstadisticas.setDisabledTextColor(new java.awt.Color(220, 213, 203));
        jScrollPane2.setViewportView(JTxtEstadisticas);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 320, 280));

        btnVolver.setBackground(new java.awt.Color(255, 255, 255));
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Volver.png"))); // NOI18N
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 560, 130, -1));

        jblPersonaje.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jblPersonaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 150, 210));

        btnAtras.setBackground(new java.awt.Color(142, 159, 151));
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Atras.png"))); // NOI18N
        btnAtras.setOpaque(false);
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 60, 60));

        btnAdelante.setBackground(new java.awt.Color(142, 159, 151));
        btnAdelante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Adelante.png"))); // NOI18N
        btnAdelante.setOpaque(false);
        btnAdelante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdelanteActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdelante, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 60, 60));

        jblNombArma.setBackground(new java.awt.Color(220, 213, 203));
        jblNombArma.setFont(new java.awt.Font("Viner Hand ITC", 1, 12)); // NOI18N
        jblNombArma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblNombArma.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.gray, null, null));
        jblNombArma.setOpaque(true);
        jPanel1.add(jblNombArma, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 480, 250, 40));

        jblArma.setBackground(new java.awt.Color(220, 213, 203));
        jblArma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblArma.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.gray, null, null));
        jblArma.setOpaque(true);
        jPanel1.add(jblArma, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 250, 250));

        jblArmadura.setBackground(new java.awt.Color(220, 213, 203));
        jblArmadura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblArmadura.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.gray, null, null));
        jblArmadura.setOpaque(true);
        jPanel1.add(jblArmadura, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 230, 250, 250));

        jblNombArmadura.setBackground(new java.awt.Color(220, 213, 203));
        jblNombArmadura.setFont(new java.awt.Font("Viner Hand ITC", 1, 14)); // NOI18N
        jblNombArmadura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblNombArmadura.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.gray, null, null));
        jblNombArmadura.setOpaque(true);
        jPanel1.add(jblNombArmadura, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 480, 250, 40));

        jLabel1.setBackground(new java.awt.Color(220, 213, 203));
        jLabel1.setFont(new java.awt.Font("Castellar", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Equipamiento");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, 310, 60));

        jblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoCartas.jpg"))); // NOI18N
        jblFondo.setText("fsdf");
        jPanel1.add(jblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdelanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdelanteActionPerformed
        // TODO add your handling code here:
        if(iterador<this.lista.length-1){
            this.iterador+=1;
            jblPersonaje.setIcon(new javax.swing.ImageIcon(getClass().getResource(this.lista[this.iterador].getLinkImag())));
            jblArma.setIcon(new javax.swing.ImageIcon(getClass().getResource(this.lista[this.iterador].getLinkArma())));
            this.jblNombArma.setText(this.lista[this.iterador].getNombreArma());
            this.JTxtEstadisticas.setText("Para el "+this.lista[this.iterador].getRaza()+" numero "+(this.iterador+1) +"\n"+this.lista[this.iterador].getInfo());
            this.jblArmadura.setIcon(new javax.swing.ImageIcon(getClass().getResource(this.lista[this.iterador].getLinkArmor())));
        }
    }//GEN-LAST:event_btnAdelanteActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        if(this.iterador>0){
            this.iterador-=1;
            jblPersonaje.setIcon(new javax.swing.ImageIcon(getClass().getResource(this.lista[this.iterador].getLinkImag())));
            jblArma.setIcon(new javax.swing.ImageIcon(getClass().getResource(this.lista[this.iterador].getLinkArma())));        
            this.jblNombArma.setText(this.lista[this.iterador].getNombreArma());
            this.JTxtEstadisticas.setText("Para el "+this.lista[this.iterador].getRaza()+" numero "+(this.iterador+1) +"\n"+this.lista[this.iterador].getInfo());
            this.jblArmadura.setIcon(new javax.swing.ImageIcon(getClass().getResource(this.lista[this.iterador].getLinkArmor())));
        }
    }//GEN-LAST:event_btnAtrasActionPerformed

    public JButton getBtnAdelante() {
        return btnAdelante;
    }

    public void setBtnAdelante(JButton btnAdelante) {
        this.btnAdelante = btnAdelante;
    }

    public JButton getBtnAtras() {
        return btnAtras;
    }

    public void setBtnAtras(JButton btnAtras) {
        this.btnAtras = btnAtras;
    }

    public JButton getBtnVolver() {
        return btnVolver;
    }

    public void setBtnVolver(JButton btnVolver) {
        this.btnVolver = btnVolver;
    }
    
    public JLabel getJblArma() {
        return jblArma;
    }

    public void setJblArma(JLabel jblArma) {
        this.jblArma = jblArma;
    }

    public JLabel getJblPersonaje() {
        return jblPersonaje;
    }

    public void setJblPersonaje(JLabel jblPersonaje) {
        this.jblPersonaje = jblPersonaje;
    }

    public JLabel getJblNombArma() {
        return jblNombArma;
    }

    public void setJblNombArma(JLabel jblNombArma) {
        this.jblNombArma = jblNombArma;
    }

    public JLabel getJblArmadura() {
        return jblArmadura;
    }

    public void setJblArmadura(JLabel jblArmadura) {
        this.jblArmadura = jblArmadura;
    }

    public JLabel getJblNombArmadura() {
        return jblNombArmadura;
    }

    public void setJblNombArmadura(JLabel jblNombArmadura) {
        this.jblNombArmadura = jblNombArmadura;
    }


    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea JTxtEstadisticas;
    private javax.swing.JButton btnAdelante;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel jblArma;
    private javax.swing.JLabel jblArmadura;
    private javax.swing.JLabel jblFondo;
    private javax.swing.JLabel jblNombArma;
    private javax.swing.JLabel jblNombArmadura;
    private javax.swing.JLabel jblPersonaje;
    // End of variables declaration//GEN-END:variables
}
