/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;

/**
 *
 * @author Johan Fontecha, Diana Ferraro, Andres Quintero
 */
public class frmPersonajes extends javax.swing.JFrame {

    /**
     * Creates new form frmPersonajes
     */
    public frmPersonajes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnHumano = new javax.swing.JButton();
        btnElfo = new javax.swing.JButton();
        btnEnano = new javax.swing.JButton();
        btnMago = new javax.swing.JButton();
        btnOrco = new javax.swing.JButton();
        lblFondo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setBackground(new java.awt.Color(220, 213, 203));
        lblTitulo.setFont(new java.awt.Font("Castellar", 1, 36)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Selección de Personajes");
        lblTitulo.setOpaque(true);
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 580, 50));

        btnHumano.setFont(new java.awt.Font("Centaur", 1, 28)); // NOI18N
        btnHumano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Humano.jpg"))); // NOI18N
        btnHumano.setText("Humano");
        btnHumano.setToolTipText("Humano");
        btnHumano.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHumano.setFocusPainted(false);
        btnHumano.setFocusable(false);
        btnHumano.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHumano.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnHumano.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHumano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHumanoActionPerformed(evt);
            }
        });
        jPanel1.add(btnHumano, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 160, 260));

        btnElfo.setFont(new java.awt.Font("Centaur", 1, 28)); // NOI18N
        btnElfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Elfo.jpg"))); // NOI18N
        btnElfo.setText("Elfo");
        btnElfo.setToolTipText("Elfo");
        btnElfo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnElfo.setFocusPainted(false);
        btnElfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnElfo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnElfo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(btnElfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 160, 260));

        btnEnano.setFont(new java.awt.Font("Centaur", 1, 28)); // NOI18N
        btnEnano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Enano.jpg"))); // NOI18N
        btnEnano.setText("Enano");
        btnEnano.setToolTipText("Enano");
        btnEnano.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEnano.setFocusPainted(false);
        btnEnano.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEnano.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnEnano.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(btnEnano, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 160, 260));

        btnMago.setFont(new java.awt.Font("Centaur", 1, 28)); // NOI18N
        btnMago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Mago.png"))); // NOI18N
        btnMago.setText("Mago");
        btnMago.setToolTipText("Mago");
        btnMago.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMago.setFocusPainted(false);
        btnMago.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMago.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnMago.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(btnMago, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, 160, 260));

        btnOrco.setFont(new java.awt.Font("Centaur", 1, 28)); // NOI18N
        btnOrco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Orco.jpg"))); // NOI18N
        btnOrco.setText("Orco");
        btnOrco.setToolTipText("Orco");
        btnOrco.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnOrco.setFocusPainted(false);
        btnOrco.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOrco.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnOrco.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(btnOrco, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 180, 160, 260));

        lblFondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPersonaje.jpg"))); // NOI18N
        lblFondo2.setMaximumSize(new java.awt.Dimension(1200, 674));
        lblFondo2.setMinimumSize(new java.awt.Dimension(1200, 674));
        lblFondo2.setPreferredSize(new java.awt.Dimension(1200, 674));
        jPanel1.add(lblFondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 674));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHumanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHumanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHumanoActionPerformed

    public JButton getBtnElfo() {
        return btnElfo;
    }

    public void setBtnElfo(JButton btnElfo) {
        this.btnElfo = btnElfo;
    }

    public JButton getBtnEnano() {
        return btnEnano;
    }

    public void setBtnEnano(JButton btnEnano) {
        this.btnEnano = btnEnano;
    }

    public JButton getBtnHumano() {
        return btnHumano;
    }

    public void setBtnHumano(JButton btnHumano) {
        this.btnHumano = btnHumano;
    }

    public JButton getBtnMago() {
        return btnMago;
    }

    public void setBtnMago(JButton btnMago) {
        this.btnMago = btnMago;
    }

    public JButton getBtnOrco() {
        return btnOrco;
    }

    public void setBtnOrco(JButton btnOrco) {
        this.btnOrco = btnOrco;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnElfo;
    private javax.swing.JButton btnEnano;
    private javax.swing.JButton btnHumano;
    private javax.swing.JButton btnMago;
    private javax.swing.JButton btnOrco;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFondo2;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
